name: Cypress cache test
on:
  # Allow the workflow to be reusable
  workflow_call:
  # Allow the workflow to be manually triggered
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Download and cache distribution of the requested Node.js version, and add it to the PATH
      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Install a
        id: echo
        env:
          OUTPUT1: ${{ github.ref_name }}
        run: |
          echo $OUTPUT1

      # Cache dependencies to speed up workflow
      # path: The file path on the runner to cache or restore.
      # key: Create cache key using the hashFiles function to create a new cache when dependencies change.
      # restore-keys: An ordered list of alternative keys to use for finding the cache if no cache hit occurred for key
      - name: Cache dependencies
        id: cache-node-modules
        if: (github.ref_name != 'main') && (github.ref_name != 'master')
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-modules-${{ github.ref_name }}-
              ${{ runner.os }}-modules-

      # Install dependencies when the cache has not been retrieved
      - name: Install dependencies
        id: install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

        # # Install NPM dependencies, cache them correctly
        # # and run all Cypress tests
        # - name: Cypress run
        #   uses: cypress-io/github-action@v4
        #   with:
        #     install: false
        #     browser: chrome
        #     headed: true
        #   env:
        #     TEST_EMAIL: ${{secrets.TEST_EMAIL}}
        #     TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
        #     REACT_APP_GRAASP_PERFORM_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_PERFORM_HOST_STAGE}}
        #     REACT_APP_GRAASP_COMPOSE_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_COMPOSE_HOST_STAGE}}
        #     REACT_APP_GRAASP_EXPLORE_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_EXPLORE_HOST_STAGE}}
        #     REACT_APP_AUTHENTICATION_HOST_STAGE: ${{secrets.REACT_APP_AUTHENTICATION_HOST_STAGE}}
