name: Cypress cache test
on:
  # Allow the workflow to be reusable
  workflow_call:
  # Allow the workflow to be manually triggered
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Download and cache distribution of the requested Node.js version, and add it to the PATH
      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Install a
        id: echo
        env:
          OUTPUT1: ${{ github.ref_name }}
        run: |
          echo $OUTPUT1

      - name: Install a
        id: a
        env:
          OUTPUT1: ${{ github.ref_name == 'main' }}
          OUTPUT2: ${{ github.ref_name == 'master' }}
        if: ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'master' }}
        run: |
          echo $OUTPUT1
          echo $OUTPUT2

      - name: Install b
        id: b
        env:
          OUTPUT1: ${{ github.ref_name == 'main' }}
          OUTPUT2: ${{ github.ref_name == 'master' }}
        if: ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'master' }}
        run: |
          echo $OUTPUT1
          echo $OUTPUT2

      - name: Install c
        id: c
        env:
          OUTPUT1: ${{ github.ref_name == 'main' }}
          OUTPUT2: ${{ github.ref_name == 'master' }}
        if: ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'master' }}
        run: |
          echo $OUTPUT1
          echo $OUTPUT2

      - name: Install d
        id: d
        env:
          OUTPUT1: ${{ github.ref_name == 'main' }}
          OUTPUT2: ${{ github.ref_name == 'master' }}
        if: ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'master' }}
        run: |
          echo $OUTPUT1
          echo $OUTPUT2

      - name: Install dependencies
        id: install
        if: ${{ github.ref_name == 'main' }} || ${{ github.ref_name == 'master' }}
        run: yarn install

        # # Install NPM dependencies, cache them correctly
        # # and run all Cypress tests
        # - name: Cypress run
        #   uses: cypress-io/github-action@v4
        #   with:
        #     install: false
        #     browser: chrome
        #     headed: true
        #   env:
        #     TEST_EMAIL: ${{secrets.TEST_EMAIL}}
        #     TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
        #     REACT_APP_GRAASP_PERFORM_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_PERFORM_HOST_STAGE}}
        #     REACT_APP_GRAASP_COMPOSE_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_COMPOSE_HOST_STAGE}}
        #     REACT_APP_GRAASP_EXPLORE_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_EXPLORE_HOST_STAGE}}
        #     REACT_APP_AUTHENTICATION_HOST_STAGE: ${{secrets.REACT_APP_AUTHENTICATION_HOST_STAGE}}
