name: Deploy new stack to staging environment

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    environment: 
      name: staging
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get latest versions file
      id: latest-file
      run: |
        cd ./release-versions
        LATEST_FILE_NAME=$(ls -Ar | head -n 1)
        echo ::set-output name=latest::${LATEST_FILE_NAME}

    - name: Generate matrix
      id: set-matrix
      env:
        LATEST_FILE_NAME: ${{ steps.latest-file.outputs.latest }}
      run: |
        echo ::set-output name=matrix::${LATEST_FILE_NAME//'%'/'%25'}

  dispatch:
    name: Dispatch Continuous Delivery workflows
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
    - run: echo ${{matrix.repo}}

    - run: echo ${{matrix.tag}}

    - name: Set json output
      id: set-json
      env:
        TAG: ${{matrix.tag}}
      run: |
        JSON=$(jq --null-input --arg tag "$TAG" '{"tag": $tag}')
        echo ::set-output name=json::${JSON//'%'/'%25'}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ matrix.repo }}
        event-type: staging-deployment
        client-payload: ${{steps.set-json.outputs.json}}

    - name: Check api Version and Status before next dispatch
      if:  ${{ matrix.repo == 'victorggonzalez/example-voting-app' }} 
      run: sleep 60
