name: Check API status

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [check-status]

env:
  TAG: ${{ github.event.client_payload.tag }}
  attemptNumber: ${{ github.event.client_payload.attemptNumber }}

jobs:
  doTheRestOfTheWork:
    name: Check Api
    runs-on: ubuntu-latest  
    steps:
    - name: Get the next attempt number
      id: getNextAttemptNumber
      uses: cardinalby/js-eval-action@v1
      env:
        maxAttempts: '5'
      with:
        expression: |
          {
            const 
              attempt = parseInt(env.attemptNumber),
              max = parseInt(env.maxAttempts);
            assert(attempt && max && max >= attempt);
            return attempt < max ? attempt + 1 : '';
          }
    - uses: actions/checkout@v2

    - name: test input
      id: test-input
      run: |
        echo $TAG
        echo $attemptNumber

    - name: Check api Version and Status before next dispatch
      id: get-status
      run: echo "::set-output name=status::$(curl -s https://api.graasp.org/status)"

    # ## Do your job here
    # - name: Fake work
    #   id: workStep
    #   if:  ${{ steps.get-status.outputs.status == env.TAG }} 
    #   with:
    #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #     repository: victorggonzalez/workflows
    #     event-type: check-status
    #     client-payload: '{"tag": "${{ env.TAG }}", "attemptNumber": "${{steps.getNextAttemptNumber.outputs.result}}"}'

    ## Do your job here
    - name: Fake work
      id: actualWorkStep
      if:  ${{ steps.get-status.outputs.status != env.TAG }} 
      continue-on-error: true
      run: |
        sleep 30
        'exit 1'

    ## Call itself again
    - name: Trigger next dispatch
      uses: peter-evans/repository-dispatch@v2
      ## If actualWorkStep failed and maxAttempts hasn't 
      ## been reached
      if: |
        steps.actualWorkStep.outcome != 'success' &&
        steps.getNextAttemptNumber.outputs.result
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: victorggonzalez/workflows
        event-type: check-status
        client-payload: '{"tag": "${{ env.TAG }}", "attemptNumber": "${{steps.getNextAttemptNumber.outputs.result}}"}'
