name: Test needs
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test-execution:
        type: boolean
        default: true
        description: 'Execute test job (Default: yes)'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: The job has failed
      if: ${{ failure() }}
      run: echo fails

  test:
    runs-on: ubuntu-latest
    if: inputs.test-execution == true
    needs: build
    steps:
      - run: echo ${{ needs.build.result }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - run: echo ${{ needs.build.result }}
      - run: echo ${{ needs.test.result }}
