name: Test needs
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test-execution:
        type: boolean
        default: true
        description: 'Execute test job (Default: yes)'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: The job has failed
      if: ${{ failure() }}
      run: echo fails

  test:
    runs-on: ubuntu-latest
    if: inputs.test-execution == true
    needs: build
    steps:
      - run: echo ${{ needs.build.result }}

  deploy1:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: ${{ always() && ((github.event_name == 'workflow_dispatch') || (github.ref_name == 'main') || (github.ref_name == 'master')) }}
    steps:
      - run: echo ${{ needs.build.result }}
      - run: echo ${{ needs.test.result }}

  deploy2:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: ${{ needs.build.result == 'success' && ((github.event_name == 'workflow_dispatch') || (github.ref_name == 'main') || (github.ref_name == 'master')) }}
    steps:
      - run: echo ${{ needs.build.result }}
      - run: echo ${{ needs.test.result }}
