# This workflow triggers a new workflow inside the graasp-deploy repository. It passes a json 
# with the repository name and the latest tag pushed from the caller repository. 
name: Push new tag to graasp-deploy repository

# Controls when the action will run
on:
  # Allow the workflow to be manually triggered
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release-type:
        # Description to be shown in the UI instead of 'stack'
        description: 'Select a release type'
        # Default value if no value is explicitly provided
        # Input does not have to be provided for the workflow to run
        type: choice
        options: 
        - first
        - patch        
        - minor        
        - major
        default: patch
        required: true
# Set environment variables that are available to the steps of all jobs in the workflow
env:
  SHOULD_DEPLOY: (github.event_name == 'workflow_dispatch') || (github.ref_name == 'main') || (github.ref_name == 'master')

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-update-staging-version-workflow:
    # Replace with repository name
    name: Update staging version caller template
    steps:
    - name: Echo release type
      env: 
        RELEASE_TYPE: ${{ inputs.release-type }}
      run: |
        echo $RELEASE_TYPE
        echo $SHOULD_DEPLOY
