name: stack to staging environment

# Controls when the action will run.
on:
  repository_dispatch:
    types: [deploy-stack]

env:
  LATEST_FILE_NAME:  ${{ github.event.client_payload.file }}

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate matrix
      id: set-matrix
      run: |
        cd ./release-versions
        LATEST_FILE=$(cat $LATEST_FILE_NAME)
        echo ::set-output name=matrix::${LATEST_FILE//'%'/'%25'}

    - run: echo "$MATRIX"
      env:
        MATRIX: ${{tojson( steps.set-matrix.outputs.matrix)}}

  dispatch:
    name: Dispatch Continuous Delivery workflows
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        ${{ insert }}: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
        exclude:
          # excludes example-voting-app
          - repo: victorggonzalez/example-voting-app
    steps:
    - run: echo ${{matrix.repo}}

    - run: echo ${{matrix.tag}}

    - name: Set json output
      id: set-json
      env:
        TAG: ${{matrix.tag}}
      run: |
        JSON=$(jq --null-input --arg tag "$TAG" '{"tag": $tag}')
        echo ::set-output name=json::${JSON//'%'/'%25'}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ matrix.repo }}
        event-type: staging-deployment
        client-payload: ${{steps.set-json.outputs.json}}

    - name: Check api Version and Status before next dispatch
      if:  ${{ matrix.repo == 'victorggonzalez/example-voting-app' }} 
      run: sleep 60
