name: TEST new backend to staging environment

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      fileName: ${{ steps.latest-file.outputs.latest }}
    environment: 
      name: staging
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get latest versions file
      id: latest-file
      run: |
        cd ./release-versions
        LATEST_FILE_NAME=$(ls -Ar | head -n 1)
        echo ::set-output name=latest::${LATEST_FILE_NAME}

    - name: Generate matrix
      id: set-matrix
      env:
        LATEST_FILE_NAME: ${{ steps.latest-file.outputs.latest }}
      run: |
        cd ./release-versions
        LATEST_FILE=$(cat $LATEST_FILE_NAME)
        echo ::set-output name=matrix::${LATEST_FILE//'%'/'%25'}

    - run: echo "$MATRIX"
      env:
        MATRIX: ${{tojson( steps.set-matrix.outputs.matrix)}}

  dispatch-backend:
    name: Dispatch Continuous Delivery workflow in backend
    needs: generate-matrix
    runs-on: ubuntu-latest
    env: 
      REPO: ${{fromJson(needs.generate-matrix.outputs.matrix).include[0].repo}}
      TAG: ${{fromJson(needs.generate-matrix.outputs.matrix).include[0].tag}}
      LATEST_FILE_NAME: ${{needs.generate-matrix.outputs.fileName}}
    steps:
    - name: test matrix
      id: test-matrix
      run: |
        echo $REPO
        echo $TAG
        echo $LATEST_FILE_NAME

    - name: Set json output
      id: set-json
      env:
        TAG: ${{fromJson(needs.generate-matrix.outputs.matrix).include[0].tag}}
      run: |
        JSON=$(jq --null-input --arg tag "$TAG" '{"tag": $tag}')
        echo ::set-output name=json::${JSON//'%'/'%25'}

    # Dispatch deployment
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{fromJson(needs.generate-matrix.outputs.matrix).include[0].repo}}
        event-type: staging-deployment
        client-payload: ${{steps.set-json.outputs.json}}
    
    # Dispatch status check
    - name: Dispatch Api status check
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: victorggonzalez/workflows
        event-type: check-status
        client-payload: '{"tag": "${{ env.TAG }}", "file": "${{ env.LATEST_FILE_NAME }}", "attemptNumber": 1}'
