name: Dispatch workflow on other repo

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test job
      run: |
        cat payload.json

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: victorggonzalez/example-voting-app
        event-type: staging-deployment
        client-payload: ./payload.json
