name: CI - Integration Test 

# Controls when the action will run. 
# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

env:        
  PASSWORD: ${{ secrets.STAGING_PASSWORD }}
  EMAIL: ${{ secrets.STAGING_EMAIL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout 
      uses: actions/checkout@v2

    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true

    - name: Setup runner
      id: setup-runner
      run: |
        npm uninstall -g newman
        npm install --location=global newman newman-reporter-htmlextra
        echo 'here'
        newman --version

    - name: Setup environment secrets
      id: setup-secrets
      run: |
        cd postman
        cat postman_environment.json | jq -r --arg password "$PASSWORD" --arg email "$EMAIL" \
        '.values[0].value |= $password | .values[1].value|= $email' > staging.postman_environment.json

    - name: Run newman
      id: newman
      run: |
        newman run postman/GraaspAPITest.postman_collection.json -e postman/staging.postman_environment.json -r htmlextra
        echo 'here'

    - name: git status
      id: status
      run: |
        git status
        ls -l
        cd newman
        ls -l

    # - name: Commit step
    #   id: commit
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: First commit
    #     file_pattern: postman-report.html 
