name: CI - Integration Test 

# Controls when the action will run. 
# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

env:        
  PASSWORD: ${{ secrets.STAGING_PASSWORD }}
  EMAIL: ${{ secrets.STAGING_EMAIL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout 
      uses: actions/checkout@v2

    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true

    - name: Setup environment secrets
      id: setup-secrets
      run: |
        cat postman_environment.json | jq -r --arg password "$PASSWORD" --arg email "$EMAIL" \
        '.values[0].value |= $password | .values[1].value|= $email' > staging_environment.json

    - name: Run newman
      id: newman
      run: |
        newman --version
        npm install --location=global newman-reporter-html
        newman run graasp-deploy-test.json -e staging_environment.json --reporters cli,html --reporter-html-export postman-report.html  

    - name: HTML Preview
      id: html-preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: 'postman-report.html'
