name: CI S3 reusable repo

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [update-staging-version]
  workflow_dispatch:

env:
  VERSION: ${{ github.event.client_payload.voting-app-tag }}

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test job
      id: set-json
      run: |
        echo $VERSION
        echo '${{ toJson(github) }}'