name: see sw installed

# Controls when the action will run. 
# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout 
      uses: actions/checkout@v2

    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        check-latest: true

    - name: setup
      id: setup
      run: |
        sudo npm install -g newman-reporter-htmlextra
        npm list
        ls -l
        npm root -g
        cd /opt/hostedtoolcache/node/16.16.0/x64/lib/node_modules
        ls -l

    - name: newman action
      uses: matt-ball/newman-action@master
      with:
        collection: collection.postman_collection.json
        reporters: '["htmlextra"]'
