name: see sw installed

# Controls when the action will run. 
# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    uses: victorggonzalez/workflows/.github/workflows/integration-test.yml@main
  cypress:
    name: Cypress
    needs: test
    uses: victorggonzalez/workflows/.github/workflows/e2e-test.yml@4989494745fcd346cb76c6e157827220e9c158ea

    # # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    # - name: Git checkout 
    #   uses: actions/checkout@v2

    # - name: Setup node
    #   id: setup-node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'
    #     check-latest: true

    # - name: setup
    #   id: setup
    #   run: |
    #     npm install newman newman-reporter-htmlextra
    #     npm list

    # - name: newman action
    #   run: |
    #     node_modules/newman/bin/newman.js run collection.postman_collection.json -r cli,htmlextra
    #     git status

    # - name: Run API Tests
    #   id: run-newman
    #   uses: anthonyvscode/newman-action@v1
    #   with:
    #     collection: collection.postman_collection.json
    #     reporters: cli,html,htmlextra

    # - name: Commit step
    #   id: commit
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: 'test commit'
    #     file_pattern: newman/*
