name: test trigger stage new stack to staging environment

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  mock:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # This step runs a single command to execute integation testing
    - name: Test
      run: |
        echo "This is the integration test step"
  test:
    needs: mock
    uses: victorggonzalez/workflows/.github/workflows/sw-fw.yml@main
    secrets: inherit
