name: 1- test

# Controls when the action will run. 
# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  # Allow the workflow to be reusable
  workflow_call:
  schedule:
    - cron: '0 8 * * *'
env:
  GH_PAGES_ENDPOINT: 'https://victorggonzalez.github.io/workflows/'

jobs:
  set-up:
    name: Set up
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set-date.outputs.date }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - id: set-date
      run: |
        DATE=$(echo "`date +"%Y-%m-%d-%H-%M"`")
        echo ::set-output name=date::$DATE

  smoke-test:
    name: Smoke Test
    needs: set-up
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:        
      DATE: ${{ needs.set-up.outputs.date }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Check-out repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Git checkout 
      uses: actions/checkout@v3

    # Download and cache distribution of the requested Node.js version, and add it to the PATH
    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        check-latest: true

    # Setup the runner with the appropriate packages
    - name: Setup runner
      id: setup-runner
      run: |
        npm install newman newman-reporter-htmlextra

    # Run a set of commands using the runners shell to perform tests
    - name: Run newman
      id: newman
      continue-on-error: true
      run: |
        FILE_NAME=$(echo $DATE-smoke-test-run.html)
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        node_modules/newman/bin/newman.js run postman/GraaspSmokeTest.postman_collection.json -r htmlextra --reporter-htmlextra-export ./newman/smoke-test/$FILE_NAME

    - name: Generate job summary markdown
      env:
        FILE_NAME: ${{ env.FILE_NAME }}
      if: always()
      run: |
        echo '[See smoke test summary in github pages](${{env.GH_PAGES_ENDPOINT}}newman/smoke-test/${{ env.FILE_NAME }})' >> $GITHUB_STEP_SUMMARY
        echo 'Please wait for the github pages deployment to finish (this can take around 2 minutes).' >> $GITHUB_STEP_SUMMARY

    - name: Commit step
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Staging test run ${{ env.DATE }}'
        branch: gh-pages
        file_pattern: newman/*

  api-test:
    name: Graasp API Test
    needs: [set-up]
    runs-on: ubuntu-latest
    env:        
      PASSWORD: ${{ secrets.STAGING_PASSWORD }}
      EMAIL: ${{ secrets.STAGING_EMAIL }}
      API_HOST: ${{ secrets.REACT_APP_API_HOST_STAGE }}
      DATE: ${{ needs.set-up.outputs.date }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Git checkout 
      uses: actions/checkout@v3

    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        check-latest: true

    - name: Setup runner
      id: setup-runner
      run: |
        npm install newman newman-reporter-htmlextra

    # Set environment variables required to perform the tests
    - name: Setup environment secrets
      id: setup-secrets
      run: |
        cat postman/postman_environment.json | jq -r --arg password "$PASSWORD" --arg email "$EMAIL" --arg api_host "$API_HOST" \
        '.values[0].value |= $password | .values[1].value|= $email | .values[2].value|= $api_host' > postman/staging.postman_environment.json

    # Run a set of commands using the runners shell to perform tests
    - name: Run newman
      id: newman
      continue-on-error: true
      run: |
        FILE_NAME=$(echo $DATE-api-test-run.html)
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        node_modules/newman/bin/newman.js run postman/GraaspAPITest.postman_collection.json -e postman/staging.postman_environment.json -r htmlextra --reporter-htmlextra-export ./newman/api-test/$FILE_NAME

    - name: Generate job summary markdown
      env:
        FILE_NAME: ${{ env.FILE_NAME }}
      # if: always()
      run: |
        echo '[See API test summary here](${{env.GH_PAGES_ENDPOINT}}newman/api-test/${{ env.FILE_NAME }})' >> $GITHUB_STEP_SUMMARY
        echo 'Please wait for the github pages deployment to finish (this can take around 2 minutes).' >> $GITHUB_STEP_SUMMARY

    - name: Commit step
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Staging test run ${{ env.DATE }}'
        branch: gh-pages
        file_pattern: newman/*

  cypress-run:
    name: End-to-End Test
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: true
        env:
          TEST_EMAIL: ${{secrets.TEST_EMAIL}}
          TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
          REACT_APP_GRAASP_PERFORM_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_PERFORM_HOST_STAGE}}
          REACT_APP_GRAASP_COMPOSE_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_COMPOSE_HOST_STAGE}}
          REACT_APP_GRAASP_EXPLORE_HOST_STAGE: ${{secrets.REACT_APP_GRAASP_EXPLORE_HOST_STAGE}}
          REACT_APP_AUTHENTICATION_HOST_STAGE: ${{secrets.REACT_APP_AUTHENTICATION_HOST_STAGE}}
