name: Update staging versions

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [update-staging-version]

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create new stagingVersions.json file
      env:
        REPOSITORY: ${{ github.event.client_payload.repo }}
        VERSION: ${{ github.event.client_payload.tag }}
      run: | 
        echo "FILE_NAME=$(echo "`date +"%Y%m%d%H%M"`"-stagingVersions.json)" >> $GITHUB_ENV
        echo $FILE_NAME 
        jq --arg version "$VERSION" --arg repository "$REPOSITORY" \
        '(.include[] | select(.repo == $repository) | .tag) |= $version' ./release-versions/matrix.json > ./release-versions/$FILE_NAME

    - name: Commit step
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.FILE_NAME }}


