name: Update staging versions

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  repository_dispatch:
    types: [update-staging-version]

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get latest versions file
      id: latest-file
      run: |
        cd ./staging-versions
        LATEST_FILE_NAME=$(ls -Ar | head -n 1)
        echo ::set-output name=latest::${LATEST_FILE_NAME}

    - name: Create new staging-versions.json file
      env:
        REPOSITORY: ${{ github.event.client_payload.repo }}
        TAG: ${{ github.event.client_payload.tag }}
        LATEST_FILE_NAME: ${{ steps.latest-file.outputs.latest }}
      run: | 
        FILE_NAME=$(echo "`date +"%Y%m%d%H%M"`"-staging-versions.json)
        echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        jq --arg tag "$TAG" --arg repository "$REPOSITORY" \
        'if ((.include[] | select(.repository == $repository)) // null) != null then (.include[] | select(.repository == $repository) | .tag) |= $tag else .include += [{"repository": $repository, "tag": $tag}] end' \
        ./staging-versions/$LATEST_FILE_NAME > ./staging-versions/$FILE_NAME

    - name: Commit step
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.FILE_NAME }}
        # jq --arg tag "$TAG" --arg repository "$REPOSITORY" \
        # '(.include[] | select(.repository == $repository) | .tag) |= $tag' ./staging-versions/$LATEST_FILE_NAME > ./staging-versions/$FILE_NAME
